# Generated by Django 6.0.5 on 2026-05-12 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageCash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensemodel',
            old_name='amoumt',
            new_name='amount',
        ),
    ]
