# Generated by Django 6.0.5 on 2026-05-12 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageCash', '0002_rename_amoumt_expensemodel_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashmodel',
            old_name='amoumt',
            new_name='amount',
        ),
    ]
